inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/IndexedLet:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - as
    - "on"
