inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/IndexedLet:
  Enabled: false
